Fix/bluetooth
energietransitie/twomes-app-needforheat pull request #64
Opened 2024-03-15 17:47 UTC by MeriyemBilgili

### Checklist

- [ ] Tests have been written/updated (if necessary)
  - [ ] All tests are passing
- [ ] Docs have been updated (if necessary)
- [ ] Updated `Linear` issue to `In Review`

### Description

The issue with turning on Bluetooth has been resolved. To enable Bluetooth, you need to click on the 'Enable Bluetooth' button. You will then be redirected to the Bluetooth page on your mobile phone to enable Bluetooth there.

### Linked Issues

### Additional context

2024-03-18 19:10 UTC, Labhatorian requested changes
Need to make sure people know to add nearby devices permission too. Otherwise, it seems to work fine when I test it. No crashes and I get told which permissions need to be added + enable bluetooth.

Btw, you don't need to remake a PR for this. new commits will get added

2024-03-18 19:10 UTC, Labhatorian commented on apps/expo/src/lang/nl-NL.json
>              "message": "Deze app gebruikt Bluetooth, maar registreert uw locatie niet. Op Android valt Bluetooth onder locatiediensten. Daarom krijgt u zo een vraag over locatie.",
Should mention nearby devices permission too

2024-03-18 19:10 UTC, Labhatorian commented on apps/expo/src/lang/en-US.json
>              "message": "This app uses Bluetooth, but does not register your location. On Android devices, Bluetooth is considered part of location services. That's why you will get a question about l
Should mention nearby devices permission too

2024-03-20 11:21 UTC, Labhatorian approved these changes
I've tested it and it works for me

2024-03-20 19:27 UTC, Labhatorian requested changes
Just tested it on iOS. It behaves differently but not in a bad way, I believe the main non-happy flow was on Android.
iOS is good enough to help people understand they need Bluetooth turned on.

2024-03-20 19:27 UTC, Labhatorian commented on apps/expo/src/lang/nl-NL.json
> +            "message": "Deze app maakt gebruik van Bluetooth, maar registreert uw locatie niet. Op Android valt Bluetooth onder locatiediensten. Daarom zult u binnenkort een vraag krijgen over locati
This line shows on iOS too.
iOS only needs Bluetooth and Location and we probably should not mention Android.

2024-03-20 19:27 UTC, Labhatorian commented on apps/expo/src/screens/home/SearchDeviceScreen.tsx
>        Platform.OS === "ios"
Reuse this to change the line I mentioned

2024-03-27 18:03 UTC, Labhatorian approved these changes
Should now be fixed for iOS too Since I worked on it too, I'll approve it but someone else should still check.

2024-03-28 09:42 UTC, ThomasBuh approved these changes

2024-03-28 10:09 UTC, Niels995 commented on apps/expo/src/screens/home/SearchDeviceScreen.tsx
> +    console.log(hasBluetoothPermission);
Dont leave console.log in the final code...

2024-03-28 14:04 UTC, Niels995 approved these changes

2024-03-28 14:12 UTC, merged